language: java
before_script:
- unset _JAVA_OPTIONS
- cd finish
- chmod +x ../scripts/travisTest.sh
script:
- ../scripts/travisTest.sh
after_script:
- logsPath=$(find . -name "console.log" | sed "s/console.log//g");
- build=$(grep "Open Liberty" $logsPath/console.log | cut -d" " -f5 | cut -d")" -f1 );
- release=$( echo "$build" | cut -d'/' -f1); 
- number=$(echo "$build" | cut -d'/' -f2); 
- ol_jv=$(grep -i "version" $logsPath/console.log);
- jv=$(printf '%s\n' "${ol_jv//$' on '/$'\n'}" | sed '2q;d'); 
- echo -e "\n"\
  "\033[1;34m Open Liberty release:\033[0m\033[1;36m $release \033[0m \n"\
  "\033[1;34m Open Liberty build number:\033[0m\033[1;36m $number \033[0m \n"\
  "\033[1;34m Java version:\033[0m\033[1;36m $jv \033[0m \n"
- cd $logsPath;
- repo_name=$(echo "$TRAVIS_REPO_SLUG" | sed -e "s/\//-/g"); 
- if [ "$TRAVIS_TEST_RESULT" -eq 0 ]; then RESULT="passed"; else RESULT="failed"; fi;
- echo -e "\033[1;34m result:\033[0m\033[1;36m $RESULT \033[0m \n"
- serverlogsarchive="$repo_name-$TRAVIS_BUILD_NUMBER-$RESULT.zip";
- if [ "$TRAVIS_TEST_RESULT" -eq 0 ]; then echo skipped to zip $serverlogsarchive; else zip -r "$serverlogsarchive" .; fi;
- if [ "$TRAVIS_TEST_RESULT" -eq 0 ]; then echo skipped upload; else curl -H "$JFROG_TOKEN" -T "$serverlogsarchive" "https://na.artifactory.swg-devops.com/artifactory/hyc-openliberty-guides-files-generic-local/"; fi;
notifications:
  slack:
    template:
    - 'Build: <%{build_url}| %{build_number}> | Commit (<%{compare_url}|%{commit}>):
      %{commit_message}'
    - 'Repo@Branch: %{repository_slug}@%{branch}'
    - 'Author: %{author}'
    - 'Summary: %{result} in %{duration}'
    rooms:
      secure: XbNXWScUdU3dx6ZP7nWJHcrTHL4904fqhQFsrFuQ+wIigZeN1SU0TJ6aN+H1oji6Oew/XT/ezg3YkcBLony9h8a+vNCuotx3uRv1HNEPbjeJFGFsoxRSgjBna1WMibIcTRhm8bsQOBgJILulNZa0qPFmF+lI9KehYVWb3plHmNUMIrVtOWgW0IkqeLCD12FUtOsY9W2RytoGv5g60XP4o/rwKI1HJQ6wMdAt7J+GL/5Hwmr5UVU3c87sMcxAJ8IsugpM1/7dHon3DF6fmmOObUbBMuMozYVAib6YNEVg7Bt3W8tOsysTYsFHcIrUwNPkK17M3lABIsVHSDeHlpII37q/2OkNCiKXm6TgsdtGjpfhPqzXmvlnPUHL/g8QD2tLsIsCT8dIE+Sy7mq/8GgDDoqihSSFTpdAk52ONp+YMtoQX1Wuhmz9pok4H57/0SyT7yOlewUpmtf7Gix+i1ekf1mO2rFl254oG3xN0nWMnwUUOFyj/J3fjc72Z3XP6GmBd+I8ZwNz+9WHtqW9T2AZ0l1IEOrqp1I6Qt2Zl1X7topTTFjUVPa5zbcYaNmD0N3lxaWLTYw0wssEIVuTYhFVCHCadjA/O2M+DKyNCLHzEIXJlqEFgFQMZ1mOvG0iMi46xnY7ANDgPejSFcLjApaez68QHO+KRs3GQrYIv/2l5nM=
    on_success: never
    on_failure: always
branches:
  only:
  - master
  - qa
